### PR TITLE
电自2001_202030310082张淦镠Copyright ©2001-2099 All right reserved

### PR DESCRIPTION
**Pull request by skymansion**
电自2001张淦镠_202030310082_张淦镠_Copyright ©2001-2099 GanliuZhang.All right reserved

### CODE REVIEW

**Comment by skymansion** [comment]
[电自2001张淦镠_202030310082_张淦镠_Copyright ©2001-2099 GanliuZhang.All right reserved.docx](https://github.com/Xiaojiean/C-_homework/files/7193910/2001._202030310082_._Copyright.2001-2099.GanliuZhang.All.right.reserved.docx)

**Comment by Gaosong12345** [comment]
skymansion 666

**Comment by githubyrz** [comment]
emmmm

**Comment by Gaosong12345** [comment]
Ganliu Zhang nb 666

**Pull request closed without merging**
